config/routes.rb
SampleApp::Application.routes.draw do
  
  get "posts/new"
  resources :users do
    member do
      put :change,:change_join_status, :allocate,:change_last_words_status
    end
  end
  resources :sessions ,:only=> [:new ,:create, :destroy]
  resources :posts, :only=>[:create,:destroy,:index]
  root :to => 'static_pages#home'
  match "/help", :to =>'static_pages#help'
  match "/contact", :to =>'static_pages#contact'
  match "/about", :to =>'static_pages#about'
  match "/signup", :to => 'users#new'
  match "/signin", :to=> 'sessions#new'
  match "/signout", :to=> 'sessions#destroy',:via=> :delete
  match "/intermediate" ,:to=>'posts#intermediate'
  match "/night_mode" ,:to=>'posts#night_mode'
  match "/day_mode" ,:to=>'posts#day_mode'
  match "/talk_mafias" ,:to=>'posts#talk_mafias'
  match "/talk_police" ,:to=>'posts#talk_police'
  match "/talk_don" ,:to=>'posts#talk_don'
  match "/talk_doc" ,:to=>'posts#talk_doc'
  match "/deactivate" ,:to=>'posts#deactivate'  
  match "/status_update" ,:to=>'posts#status_update'
  match "/notify" ,:to => 'posts#notify'  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content,:place
  belongs_to :user
  
  validates :user_id,:presence=> true
  validates :content,:presence=>true
  validates :place,:presence=>true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password , :password_confirmation, :fake_name, :game_character,:mode_status
  has_secure_password
  has_many :posts,:dependent=> :destroy
  before_save {|user| user.email =email.downcase}
  before_save :create_remember_token
  validates :name,:presence => true, :length => {:maximum => 50}
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :password , :presence=> true, :length=> {:minimum => 6}
  validates :email,:presence => true, :format => {:with => VALID_EMAIL_REGEX},:uniqueness => {:case_sensitive =>false}
  
  private
  	def create_remember_token
    	  if !self.game_join_status
    	    self.remember_token = SecureRandom.hex
    	  end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user,:only=>[:create,:destroy]
  
  def create
    @post=current_user.posts.create!(params[:post])
  end
  
  def intermediate
    if signed_in?
      @posts=posts
      @users=User.all
      @post= current_user.posts.build
    else
      redirect_to signin_path
    end
  end
  
  def night_mode
    @users=User.all
    @users.each do |user|
      user.update_attribute('mode_status',false)    
    end
  end

  def deactivate
  end
  
  def notify
  end
    
  def day_mode
    @post= current_user.posts.build
    @users=User.all
    @users.each do |user|
      user.update_attribute('mode_status',true)    
    end
    @usersdead=User.find(:all,:conditions => {:live_status => false,:last_words => false})
  end
    
  def talk_mafias
    @post= current_user.posts.build
  end

  def talk_police
    @post= current_user.posts.build
  end

  def talk_don
    @post= current_user.posts.build
  end

  def talk_doc
    @post= current_user.posts.build
  end

  def index
    if signed_in?
      @post= current_user.posts.build
      @posts=posts
      @users=User.all
    else
      redirect_to signin_path,:notice => "Please sign in to participate in the game"
    end  
  end
    
  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user=User.find_by_email(params[:session][:email])
  if user && user.authenticate(params[:session][:password])
    sign_in user
    redirect_back_or root_path
  else
    flash.now[:error]='Invalid email/password combination'
    render 'new'
  end
end

def destroy
  sign_out
  redirect_to root_path
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def game
    if signed_in?
      @post= current_user.posts.build
      @posts=posts
    else
      redirect_to signin_path,:notice => "Please sign in to participate in the game"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,:only=> [:edit,:update]
  before_filter :correct_user,:only=> [:edit,:update]
  before_filter :admin_user,:only=> :destroy
  
  def new
    @user=User.new
  end
  
  def allocate
    n=User.count
    fake_names='Wolverine ProfessorX Rogue JeanGrey Cyclops Storm Iceman  Magneto Mystique Stryker Pyro Electro Deadpool Sabertooth Juggernaut Beast Bolt Gambit Frost Zero'.split
    game_characters='Mafia Don Villager Police Doctor'.split
    @users=User.all
    @users.each do |user|
      if user.admin?
        user.update_attribute('fake_name','Moderator')
        user.update_attribute('game_character','Moderator')
      else
        user.update_attribute('fake_name',fake_names.sample)
        user.update_attribute('game_character',game_characters.sample)
      end
    end
   sign_in User.find(params[:id])
   redirect_to intermediate_path
  end
        
  def create 
    @user=User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success]="Welcome to Mafia"
      redirect_to root_path
    else
      render 'new'  
    end
  end
  
  def edit
  end
  
  def change_join_status
    user=User.find(params[:id])
    user.toggle!(:game_join_status)
    sign_in user
    flash[:success]="Welcome to the game"
    redirect_to intermediate_path
  end
  
  def change
    user=User.find(params[:id])
    user.toggle!(:live_status)
    redirect_to posts_path
  end
  
  def change_last_words_status
    user=User.find(params[:id])  
    user.update_attribute('last_words',true)
    redirect_to posts_path        
  end
    
  def show
    @user=User.find(params[:id])
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] ="profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users=User.all
  end
  
  def destroy
    user=User.find(params[:id])
    flash[:success]="User #{user.name} destroyed"
    user.destroy
    redirect_to posts_path
  end 
  
  def kill
    redirect_to users_path
  end
  
  private
  

  	  def correct_user
  	    @user=User.find(params[:id])
  	    redirect_to root_path,:notice=>"You are not authorized to access other users profile" unless current_user?(@user) || current_user.admin?
  	  end	
  	  
  	  def admin_user 
  	    redirect_to (root_path) unless current_user.admin?
  	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block)}
    uri = URI.parse("http://limitless-mountain-5940.herokuapp.com/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token]=user.remember_token
    self.current_user=user
  end
  
  def current_user=(user)
    @current_user=user
  end
  
  def current_user
    @current_user ||=User.find_by_remember_token(cookies[:remember_token])
  end
  
  def posts
    Post.all
  end
  
  def signed_in_user
    unless signed_in?
      store_path
      redirect_to signin_path, :notice=>"Please Sign in"
    end 
  end

  def sign_out
    self.current_user=nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user?(user)
    user==current_user
  end
  
  def redirect_back_or(default)
    redirect_to session[:return_to] || default
    session.delete(:return_to)
  end
  
  def store_path
    session[:return_to]=request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def full_title(page_title) 
    base_title="Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, :alt=> user.name, :class=> "gravatar")
  end
end

app/views/layouts/_day_mode.html.erb
<% if current_user.admin? %>
  <%=link_to "Day mode",day_mode_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <a href="http://railstutorial.org/">Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", '#'%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_night_mode.html.erb
<% if current_user.admin? %>
  <%=link_to "Night mode",night_mode_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://limitless-mountain-5940.herokuapp.com/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
		<%= link_to "Mafia", root_path, :id => "logo" %>
		<nav>
			<ul class="nav pull-right">
				<li><%= link_to "home" ,root_path %></li>
				<li><%= link_to "help" ,'#' %></li>
				<% if signed_in? %>
				  <li id="fat-menu" class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
						<%= link_to "Sign out", signout_path, :method=> "delete" %>
						</li>
					</ul>
					</li>
				<% else %>
				  <li><%= link_to "Sign in",signin_path %></li>
				<% end %>
			</ul>
		</nav>
		</div>
	</div>
</header>
<div class="container">
<% flash.each do |key,value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/posts/_doctor_submit.html.erb
<%= form_for @post,:remote=>true,:class=>"doctor_chat",:html => { :id => "mafia_mohsin_akshay_gavit_doctor_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_doctor_post"%>
  </div>
  <div id="doctor_post">
  <script>
  function myDoctorFunction()
  {
    document.getElementById("doctor_post").innerHTML='<%= f.hidden_field :place, :value=> "doctor_post"  %>';
  }
  </script>
  </div>
  <%=f.submit "post",:class=>"btn btn-large btn-primary",:onclick=> 'myDoctorFunction();',:id=> "doctor_submit_button" %>
<% end %>

app/views/posts/_police_submit.html.erb
<%= form_for @post,:remote=>true,:html => { :id => "mafia_mohsin_akshay_gavit_police_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_police_post"%>
  </div>
  <div id="police_post">
  <script>
  function myPoliceFunction()
  {
    document.getElementById("police_post").innerHTML='<%= f.hidden_field :place, :value=> "police_post"  %>';
  }
  </script>
  </div>
  <%=f.submit "post",:class=>"btn btn-large btn-primary",:onclick=> 'myPoliceFunction();',:id=> "police_submit_button" %>
<% end %>

app/views/posts/_popup_box_data.html.erb
<h1>Its Day Mode!</h1>The game starts with the following dead:
    <ul>
      <% @usersdead.each do |user| %>
          <li>The <%= user.fake_name %></li>
      <% end %>
    </ul><%= link_to 'Continue', posts_path %>
    

app/views/posts/_post.html.erb
 <li>
   <% if post.user.fake_name %>
     <%= post.user.fake_name %>
   <% else %>
     <%= post.user.name %>
   <% end %>
    <%= post.content %>
</li>

app/views/posts/_user.html.erb
<li>
    <%= user.name %>
</li>

app/views/posts/day_mode.js.erb
<% broadcast "/messages/new" do %>
    $("#mafia_mohsin_akshay_gavit_mode_game").html("<%= escape_javascript render('posts/game_submit') %>");
    $("#popup_box").html("<%= escape_javascript render('posts/popup_box_data') %>");
    $('#popup_box').fadeIn("slow");
    $('<div></div>').prependTo('body').attr('id', 'overlay');
<% end %>

app/views/posts/index.html.erb
<% if signed_in? %>	
<div id="mafia_mohsin_akshay_gavit_mode_button">
<% if current_user.admin? %>
  <%=link_to "Night mode",night_mode_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
  <%=link_to "Day mode",day_mode_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>
</div>
<div id="mafia_mohsin_akshay_gavit_mode_button_mafia">
<% if current_user.admin? %>
  <%=link_to "Talk to Mafias",talk_mafias_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>
</div>

<div id="mafia_mohsin_akshay_gavit_mode_button_police">
<% if current_user.admin? %>
  <%=link_to "Talk to Police",talk_police_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>
</div>

<div id="mafia_mohsin_akshay_gavit_mode_button_don">
<% if current_user.admin? %>
  <%=link_to "Talk to Don",talk_don_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>
</div>

<div id="mafia_mohsin_akshay_gavit_mode_button_doctor">
<% if current_user.admin? %>
  <%=link_to "Talk to Doctor",talk_doc_path,:confirm=> "You sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>
</div>

<% if current_user.admin? %>
  <%=link_to "Deactivate",deactivate_path,:confirm=> "You Really sure?", :remote=>true,:method=>:post,:class=> "btn btn-large btn-primary" %>
<% end %>


<h1>
All users
</h1>
<ul class="users">
<% @users.each do |user|%>
  <li>
  <%= link_to user.name ,user %>
   <%= user.fake_name %>
   <%= user.game_character %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "delete",user,:method=>:delete,:confirm=> "You sure?" %> | <%= user.email %> | 
    <% if user.live_status? %>
      <%= link_to "kill",change_user_path(user) ,:method=> :put,:confirm=> "You sure?" %>
    <% end %>
  <% end %>
  </li>
<% end %>
</ul>

<div id="mafia_mohsin_akshay_gavit_status_update">
</div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
  </script>
<script>
$(document).ready(function(){
  $("#new_mafia_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#mafia_submit_button").click();
    }
  });
  $("#new_don_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#don_submit_button").click();
    }
  });
  $("#new_game_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#game_submit_button").click();
    }
  });
  $("#new_doctor_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#doctor_submit_button").click();
    }
  });
  $("#new_police_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#police_submit_button").click();
    }
  });  
  $("#new_last_words_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#last_words_submit_button").click();
    }
  });
 $("body").append( '<div id="popup_box"></div>' );    
});
</script>

  <ul id="mafia_mohsin_akshay_gavit_chat">
  <% @posts.each do |post|%>
  <% if post.place=="game_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_game" >
<% if current_user.mode_status? %>
<%= form_for @post,:remote=>true,:html => { :id => "mafia_mohsin_akshay_gavit_game_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=>3, :placeholder=> "compose new post..." ,:id=>"new_game_post" %>
  </div>
  <div id="game_post">
  <script>
  function myFunction()
  {
    document.getElementById("game_post").innerHTML='<%= f.hidden_field :place, :value=> "game_post"  %>';
  }
  </script>    
  </div>
  <%=f.submit "post",:class=>"btn btn-large btn-primary" ,:onclick=> 'myFunction();',:id=> "game_submit_button" %>
<% end %>
<% end %>
</div>

<% if current_user.admin? || current_user.game_character=="mafia" %>
<h1>Mafia Post </h1>
  <ul id="mafia_mohsin_akshay_gavit_chat_mafia">
  <% @posts.each do |post|%>
  <% if post.place=="mafia_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_mafia" >
<% if current_user.mode_status? %>
<%= form_for @post,:remote=>true,:class=>"mafia_chat",:html => { :id => "mafia_mohsin_akshay_gavit_mafia_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_mafia_post"%>
  </div>
  <div id="mafia_post">
  <script>
  function myMafiaFunction()
  {
    document.getElementById("mafia_post").innerHTML='<%= f.hidden_field :place, :value=> "mafia_post"  %>';
  }
  </script>
  </div>
<% end %>
<% end %>
</div>
<% end %>

<% if current_user.admin? || current_user.game_character=="Don" %>
<h1>Don Post </h1>
  <ul id="mafia_mohsin_akshay_gavit_chat_don">
  <% @posts.each do |post|%>
  <% if post.place=="don_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_don" >
<% if current_user.mode_status? %>
<%= form_for @post,:remote=>true,:class=>"don_chat",:html => { :id => "mafia_mohsin_akshay_gavit_don_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_don_post"%>
  </div>
  <div id="don_post">
  <script>
  function myDonFunction()
  {
    document.getElementById("don_post").innerHTML='<%= f.hidden_field :place, :value=> "don_post"  %>';
  }
  </script>
  </div>
<% end %>
<% end %>
</div>
<% end %>


<% if current_user.admin? || current_user.game_character=="Doctor" %>
<h1>Doctor Post </h1>
  <ul id="mafia_mohsin_akshay_gavit_chat_doctor">
  <% @posts.each do |post|%>
  <% if post.place=="doctor_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_doctor" >
<% if current_user.mode_status? %>
<%= form_for @post,:remote=>true,:class=>"doctor_chat",:html => { :id => "mafia_mohsin_akshay_gavit_doctor_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_doctor_post"%>
  </div>
  <div id="doctor_post">
  <script>
  function myDoctorFunction()
  {
    document.getElementById("doctor_post").innerHTML='<%= f.hidden_field :place, :value=> "doctor_post"  %>';
  }
  </script>
  </div>
<% end %>
<% end %>
</div>
<% end %>


<% if current_user.admin? || current_user.game_character=="Police" %>
<h1>Police Post </h1>
  <ul id="mafia_mohsin_akshay_gavit_chat_police">
  <% @posts.each do |post|%>
  <% if post.place=="police_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_police" >  
<% if current_user.mode_status? %>
<%= form_for @post,:remote=>true,:html => { :id => "mafia_mohsin_akshay_gavit_police_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=> 3, :placeholder=> "compose new post..." ,:id=>"new_police_post"%>
  </div>
  <div id="police_post">
  <script>
  function myPoliceFunction()
  {
    document.getElementById("police_post").innerHTML='<%= f.hidden_field :place, :value=> "police_post"  %>';
  }
  </script>
  </div>
<% end %>
<% end %>
</div>
<% end %>

<h1>Last Words </h1>

  <ul id="mafia_mohsin_akshay_gavit_last_words">
  <% @posts.each do |post|%>
  <% if post.place=="last_words_post" %>
  <li>
    <%= post.user.fake_name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>
<div id="mafia_mohsin_akshay_gavit_mode_last_words" >
<% if !current_user.live_status? && !current_user.last_words? %>
<%= form_for @post,:remote=>true,:html => { :id => "mafia_mohsin_akshay_gavit_last_words_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=>3, :placeholder=> "compose new post..." ,:id=>"new_last_words_post" %>
  </div>
  <div id="last_words_post">
  <script>
  function myLastWordsFunction()
  {
    document.getElementById("last_words_post").innerHTML='<%= f.hidden_field :place, :value=> "last_words_post"  %>';
  }
  </script>    
  </div>
  <%=f.submit "post",:class=>"btn btn-large btn-primary" ,:onclick=> 'myLastWordsFunction();',:id=> "last_words_submit_button" %>
<% end %>
<%= link_to 'End Last Words', change_last_words_status_user_path(current_user) ,:method=> :put,:class=> "btn btn-large btn-primary" %>

<% end %>
</div>


<% end %>

app/views/posts/intermediate.html.erb
<% if signed_in? %>	

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
  </script>

<script>
$(document).ready(function(){
  $("#new_before_game_post").keyup(function(event){
    if(event.keyCode == 13){
        $("#before_game_submit_button").click();
    }
  });
  $("body").append( '<div id="popup_box"><h1>You have been allocated names</h1>Join the game by pressing the link<%= link_to "game", posts_path %></div>' );
});
</script>

<ul id="users">
<% @users.each do |user|%>
 <% if user.game_join_status? %> 
    <%= render user %>
  <% end %>
<% end %>
<%= current_user.fake_name %>
<%= current_user.game_character %>

</ul>
<h1>Before Game Discussion</h1>
<ul id="mafia_mohsin_akshay_gavit_chat_before_game">
  <% @posts.each do |post|%>
  <% if post.place=="before_game_post" %>
  <li>
    <%= post.user.name %>
    <%= post.content %>
    </li>
  <% end %>
  <% end %>

  </ul>

<%= form_for @post,:remote=>true,:html => { :id => "mafia_mohsin_akshay_gavit_before_game_form" },:url=> {:action=> :create} do |f| %>
  <div class="field">
    <%= f.text_area :content,:rows=>3, :placeholder=> "compose new post...",:id=>"new_before_game_post" %>
  </div>
  <div id="before_game_post">
  <script>
  function myBeforeGameFunction()
  {
    document.getElementById("before_game_post").innerHTML='<%= f.hidden_field :place, :value=> "before_game_post"  %>';
  }
  </script>    
  </div>
  <%=f.submit "post",:class=>"btn btn-large btn-primary" ,:onclick=> 'myBeforeGameFunction();' ,:id=> "before_game_submit_button" %>
<% end %>

<% if current_user.admin? %>
  <%=link_to "Allocate Users", allocate_user_path(current_user),:method=> :put,:confirm=> "You sure?", :class=> "btn btn-large btn-primary" %>
  <%=link_to "Notify", notify_path,:remote=>true,:method=>:post, :class=> "btn btn-large btn-primary" %>
  
<% end %>

<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>
<% if signed_in? %>
<div class="center hero-unit">
<h1>Welcome to the Mafia</h1>
<h2>This is the home page</h2>
<% if current_user.game_join_status? %>
<%= link_to "Continue the game", intermediate_path, :class=> "btn btn-large btn-primary" %>
<% else %>
<%= link_to "Start Playing!", change_join_status_user_path(current_user),:method=> :put, :class=> "btn btn-large btn-primary" %>
<% end %>
</div>
<% else %>
<div class="center hero-unit">
<h1>Welcome to the Mafia</h1>
<h2>This is the home page</h2>
<%= link_to "Sign Up now!", signup_path, :class=> "btn btn-large btn-primary" %>
</div>

<% end %>

app/views/users/_user.html.erb
<li>
    <%= user.name %>
</li>

app/views/users/index.html.erb
<% provide(:title,'All users') %>
<h1>
All users
</h1>
<ul class="users">
<% @users.each do |user|%>
  <li>
  <%= link_to user.name ,user %>
   <%= user.fake_name %>
   <%= user.game_character %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "delete",user,:method=>:delete,:confirm=> "You sure?" %> | 
    <% if user.live_status? %>
      <%= link_to "kill",change_user_path(user) ,:method=> :put,:confirm=> "You sure?" %>
    <% end %>
  <% end %>
  </li>
<% end %>
</ul>